### ISSUE TITLE
Unable to run readsimulator

### ISSUE THREAD

**Issue by Rohit-Satyam** [wanyuac/readSimulator#1]
Hi developer!!

I was trying to use your tool to generate simulated reads for my genome however I am getting the following error:

```bash
python readSimulator.py --input PlasmoDB-56_PvivaxP01_Genome.fasta --simulator art --simulator_path /miniconda3/bin/art_illumina --outdir shredded_reads --iterations 10 --readlen 150 --opts '-m 300 -s 25 -qU 35 -nf 0 -rs 10 -ss HS20 -qs -1.5 -qs2 -2 -na'
Simulator: art at /miniconda3/bin/art_illumina
/miniconda3/bin/art_illumina --in PlasmoDB-56_PvivaxP01_Genome_refseq.fasta --rcount 23839 --len 150 --paired --out PlasmoDB-56_PvivaxP01_Genome_tmp_ -m 300 -s 25 -qU 35 -nf 0 -rs 10 -ss HS20 -qs -1.5 -qs2 -2 -na
Traceback (most recent call last):
  File "readSimulator.py", line 213, in <module>
    main()
  File "readSimulator.py", line 114, in main
    random_start = True, run = run)
  File "readSimulator.py", line 170, in simulate_reads
    with open(read2_tmp, "r") as f2:
FileNotFoundError: [Errno 2] No such file or directory: 'PlasmoDB-56_PvivaxP01_Genome_tmp_2.fq'
```
Can you help??

**Comment by sternp** [comment]
I'm also getting the same error. Did you manage to resolve it Rohit-Satyam?

**Comment by sternp** [comment]
I was specifying -ss HS20 with --readlen 150

Deleting -ss HS20 from --opts fixes it.
